name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull Docker image
        run: docker images --format '{{.Digest}}\t{{.Tag}}' bronese/webhook-bot:$ | sort -k2 -r | head -n1 | awk '{print $1}' | xargs docker pull bronese/webhook-bot:@


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Register new task definition
        run: |
          ECR_REPOSITORY=<your-ecr-repository-url>
          sed -i "s|your-ecr-repository-url|$ECR_REPOSITORY|" task-definition.json
          aws ecs register-task-definition --cli-input-json file://task-definition.json

      - name: Update service in AWS ECS
        run: |
          TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition webhookbot | jq -r '.taskDefinition.taskDefinitionArn')
          aws ecs update-service --cluster webhookbot --service webhookbot --task-definition $TASK_DEFINITION_ARN --force-new-deployment
